from teledynelecroyscope import TeledyneLeCroyScope

def main():
    scope = TeledyneLeCroyScope()
    print('Configuring the oscilloscope...')
    scope.lecroy.write(r"""vbs 'app.settodefaultsetup' """)
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("TRIG_MODE STOP")
    scope.lecroy.query("*OPC?")   
    scope.lecroy.write("C1:TRA ON")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C2:TRA OFF")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C3:TRA ON")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C4:TRA OFF")
    scope.lecroy.write("C1:COUPLING DC1M")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C3:COUPLING AC1M")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("BANDWIDTH_LIMIT C3,20MHZ")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("TIME_DIV 50US")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("MEMORY_SIZE 25K")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C1:VOLT_DIV 1V")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C3:VOLT_DIV 13mV")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("C1:TRIG_LEVEL 1500mV")
    scope.lecroy.query("*OPC?")
    scope.lecroy.write("TRIG_DELAY -200US")
    scope.lecroy.query("*OPC?")

if __name__ == "__main__":
    main()